
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Aug 23 22:39:41 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 16;
  public static final int NUMCONST = 17;
  public static final int NOTEQUAL = 39;
  public static final int GREATER = 40;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 27;
  public static final int LESS = 42;
  public static final int MINUS = 36;
  public static final int GREQ = 41;
  public static final int RPAREN = 7;
  public static final int AND = 35;
  public static final int DOUBLEPLUS = 32;
  public static final int OR = 34;
  public static final int COMMA = 8;
  public static final int CLASS = 21;
  public static final int EQUALEQUAL = 38;
  public static final int DIV = 45;
  public static final int PLUS = 11;
  public static final int LESSEQ = 43;
  public static final int IF = 14;
  public static final int LSQBRACE = 23;
  public static final int DOT = 30;
  public static final int FINDANY = 47;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 12;
  public static final int NEW = 37;
  public static final int error = 1;
  public static final int DOUBLEMINUS = 33;
  public static final int MUL = 44;
  public static final int MOD = 46;
  public static final int BREAK = 26;
  public static final int IDENT = 18;
  public static final int VOID = 13;
  public static final int FOREACH = 29;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int READ = 28;
  public static final int CHARCONST = 19;
  public static final int WHILE = 25;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 20;
  public static final int EXTENDS = 22;
  public static final int PROG = 2;
  public static final int HASHTAG = 48;
  public static final int RSQBRACE = 24;
  public static final int EQGT = 31;
  public static final int AT = 49;
  public static final int MAX = 51;
  public static final int SWAP = 50;
  public static final int PRINT = 9;
}

